[package]
name = "newton"
version = "0.0.1"
authors = ["Tracy Ma <1991md@gmail.com>"]

[lib]
name = "newton"
path = "src/newton/lib.rs"

[dependencies.gfx]
git = "http://github.com/gfx-rs/gfx-rs"

[dependencies.glfw]
git = "https://github.com/bjz/glfw-rs.git"

[dependencies.cgmath]
git = "https://github.com/bjz/cgmath-rs"

[[example]]
name = "cocos"
path = "example/cocos/main.rs"
